<?php
$host='localhost'; $user='root'; $password=''; $db='university_db';
$tmp=new mysqli($host,$user,$password);
if($tmp->connect_error) die('Database connection failed: '.$tmp->connect_error);
$tmp->query("DROP DATABASE IF EXISTS `$db`");
$tmp->query("CREATE DATABASE `$db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
$tmp->select_db($db);
$conn=$tmp;
function q($sql){ global $conn; if(!$conn->query($sql)){ die('<pre>SQL Error: '.$conn->error."\n\n$sql</pre>"); }}
function prep($sql){ global $conn; $stmt=$conn->prepare($sql); if(!$stmt){ die('<pre>Prepare Error: '.$conn->error."\n\n$sql</pre>"); } return $stmt; }
q("CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY, fullname VARCHAR(120) NOT NULL, login_id VARCHAR(40) UNIQUE NOT NULL, email VARCHAR(120) UNIQUE, password VARCHAR(255) NOT NULL, role ENUM('student','professor','registrar') NOT NULL, status ENUM('pending','approved','rejected') DEFAULT 'approved', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
q("CREATE TABLE IF NOT EXISTS colleges(id INT AUTO_INCREMENT PRIMARY KEY, college_code VARCHAR(20) UNIQUE NOT NULL, college_name VARCHAR(160) NOT NULL)");
q("CREATE TABLE IF NOT EXISTS programs(id INT AUTO_INCREMENT PRIMARY KEY, college_id INT NOT NULL, program_code VARCHAR(30), program_name VARCHAR(220) NOT NULL, FOREIGN KEY(college_id) REFERENCES colleges(id) ON DELETE CASCADE)");
q("CREATE TABLE IF NOT EXISTS students(id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, student_id VARCHAR(40) UNIQUE NOT NULL, college_id INT NOT NULL, program_id INT NOT NULL, year_level INT DEFAULT 1, semester_level INT DEFAULT 1, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(college_id) REFERENCES colleges(id), FOREIGN KEY(program_id) REFERENCES programs(id))");
q("CREATE TABLE IF NOT EXISTS professors(id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, employee_id VARCHAR(40) UNIQUE NOT NULL, college_id INT, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(college_id) REFERENCES colleges(id))");
q("CREATE TABLE IF NOT EXISTS subjects(id INT AUTO_INCREMENT PRIMARY KEY, program_id INT NOT NULL, subject_code VARCHAR(40) NOT NULL, subject_title VARCHAR(220) NOT NULL, units DECIMAL(3,1) DEFAULT 3, year_level INT NOT NULL, semester_level INT NOT NULL, FOREIGN KEY(program_id) REFERENCES programs(id) ON DELETE CASCADE)");
q("CREATE TABLE IF NOT EXISTS prerequisites(id INT AUTO_INCREMENT PRIMARY KEY, subject_id INT NOT NULL, prerequisite_subject_id INT NOT NULL, FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE, FOREIGN KEY(prerequisite_subject_id) REFERENCES subjects(id) ON DELETE CASCADE)");
q("CREATE TABLE IF NOT EXISTS sections(id INT AUTO_INCREMENT PRIMARY KEY, subject_id INT NOT NULL, professor_id INT NOT NULL, section_name VARCHAR(60) NOT NULL, school_year VARCHAR(20) DEFAULT '2026-2027', semester_level INT NOT NULL, FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE, FOREIGN KEY(professor_id) REFERENCES professors(id) ON DELETE CASCADE)");
q("CREATE TABLE IF NOT EXISTS enrollment_requests(id INT AUTO_INCREMENT PRIMARY KEY, student_id INT NOT NULL, section_id INT NOT NULL, status ENUM('pending','approved','rejected') DEFAULT 'pending', grade VARCHAR(10), remarks VARCHAR(20) DEFAULT 'ONGOING', requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY(section_id) REFERENCES sections(id) ON DELETE CASCADE)");
$cols=[['CCI','College of Computer and Informatics'],['COED','College of Education'],['CEA','College of Engineering and Architecture'],['CIT','College of Industrial Technology'],['CAS','College of Arts and Sciences']];
$stmt=prep('INSERT IGNORE INTO colleges(college_code,college_name) VALUES(?,?)'); foreach($cols as $c){$stmt->bind_param('ss',$c[0],$c[1]);$stmt->execute();}
function college_id($code){global $conn; return (int)$conn->query("SELECT id FROM colleges WHERE college_code='$code'")->fetch_assoc()['id'];}
$programs=[
['CCI','BSCS','Bachelor of Science in Computer Science'],['CCI','BSIT','Bachelor of Science in Information Technology'],['CCI','BSIS','Bachelor of Science in Information System'],
['COED','BEED','Bachelor of Elementary Education'],['COED','BSED-FIL','Bachelor of Secondary Education - Filipino'],['COED','BSED-MATH','Bachelor of Secondary Education - Mathematics'],['COED','BSED-SCI','Bachelor of Secondary Education - Science'],['COED','BSED-TLE','Bachelor of Secondary Education - TLE'],['COED','BTLED-HE','BTLEd - Home Economics'],['COED','BTLED-IA','BTLEd - Industrial Arts'],['COED','BTLED-ICT','BTLEd - Information and Communication Technology'],['COED','BTVTED-BCW','BTVTEd - Beauty Care and Wellness'],['COED','BTVTED-CP','BTVTEd - Computer Programming'],['COED','BTVTED-FSM','BTVTEd - Food and Service Management'],
['CEA','BSECE','Bachelor of Science in Electronics Engineering'],['CEA','BSARCH','Bachelor of Science in Architecture'],['CEA','BSEE','Bachelor of Science in Electrical Engineering'],['CEA','BSME-AE','Bachelor of Science in Mechanical Engineering - Automotive Engineering'],
['CIT','BIT-AD','Bachelor of Science in Industrial Technology - Architectural Drafting'],['CIT','BIT-AT','Bachelor of Science in Industrial Technology - Automotive Technology'],['CIT','BIT-CT','Bachelor of Science in Industrial Technology - Construction Technology'],['CIT','BIT-ET','Bachelor of Science in Industrial Technology - Electrical Technology'],['CIT','BIT-ELX','Bachelor of Science in Industrial Technology - Electronics Technology'],['CIT','BIT-FAT','Bachelor of Science in Industrial Technology - Fashion and Apparel Technology'],['CIT','BIT-FCMT','Bachelor of Science in Industrial Technology - Furniture and Cabinet Making Technology'],['CIT','BIT-MT','Bachelor of Science in Industrial Technology - Mechanical Technology'],['CIT','BIT-RACT','Bachelor of Science in Industrial Technology - Refrigerator and Air Conditioning Technology'],['CIT','BIT-WFT','Bachelor of Science in Industrial Technology - Welding and Fabrication Technology'],['CIT','BSAT','Bachelor of Science in Automotive Technology'],['CIT','BSHRT','Bachelor of Science in Hotel and Restaurant Technology'],['CIT','BSELT','Bachelor of Science in Electrical Technology'],['CIT','BSELX','Bachelor of Science in Electronics Technology'],['CIT','BSFDM','Bachelor in Fashion Design and Merchandising'],['CIT','BSE','Bachelor of Science in Entrepreneurship'],['CIT','BSHM','Bachelor of Science in Hospitality Management'],['CIT','BSTM','Bachelor of Science in Tourism Management'],
['CAS','BAEL','Bachelor of Arts in English Language'],['CAS','BACD','Bachelor of Arts in Community Development'],['CAS','BSBIO','Bachelor of Science in Biology (Biotechnology)'],['CAS','BSMATH','Bachelor of Science in Mathematics'],['CAS','BSMET','Bachelor of Science in Meteorology'],['CAS','BHS','Bachelor in Human Services']
];
$stmt=prep('INSERT IGNORE INTO programs(college_id,program_code,program_name) VALUES(?,?,?)'); foreach($programs as $p){$cid=college_id($p[0]); $stmt->bind_param('iss',$cid,$p[1],$p[2]);$stmt->execute();}
function program_id($code){global $conn; return (int)$conn->query("SELECT id FROM programs WHERE program_code='$code'")->fetch_assoc()['id'];}
$bscs=program_id('BSCS');
$subjects=[['ICT 102','Introduction to Computing',3,1,1],['CS 1','Programming Logic Formulation',3,1,1],['GE 1 SS','Understanding the Self',3,1,1],['GE 4 MATH','Mathematics in the Modern World',3,1,1],['GE 5 ENG','Purposive Communication',3,1,1],['GE 8 SS','Ethics',3,1,1],['GE ELEC 9','Philippine Popular Culture',3,1,1],['NSTP 1','ROTC 1 / LTS 1 / CWTS 1',3,1,1],['PE 1','Educational Gymnastics',2,1,1],['ICT 103','Computer Programming 1',3,1,2],['ICT 105','Web Systems and Technologies 1',3,1,2],['ICT 106','Discrete Structures 1',3,1,2],['GE 2 SS','Readings in Philippine History',3,1,2],['ENG 3','Speech Communication',3,1,2],['GE 3 SS','The Contemporary World',3,1,2],['PE 2','Rhythmic Activities',2,1,2],['NSTP 2','ROTC 2 / LTS 2 / CWTS 2',3,1,2]];
$stmt=prep('INSERT INTO subjects(program_id,subject_code,subject_title,units,year_level,semester_level) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM subjects WHERE program_id=? AND subject_code=?)');
foreach($subjects as $s){$stmt->bind_param('issdiiis',$bscs,$s[0],$s[1],$s[2],$s[3],$s[4],$bscs,$s[0]);$stmt->execute();}
$admin=password_hash('admin123',PASSWORD_DEFAULT); $profpass=password_hash('prof123',PASSWORD_DEFAULT); $studpass=password_hash('student123',PASSWORD_DEFAULT);
$conn->query("INSERT IGNORE INTO users(fullname,login_id,email,password,role,status) VALUES('Admin Registrar','REG-0001','registrar@gmail.com','$admin','registrar','approved')");
$conn->query("INSERT IGNORE INTO users(fullname,login_id,email,password,role,status) VALUES('Prof. Juan Cruz','PROF-0001','professor@gmail.com','$profpass','professor','approved')");
$prof_uid=(int)$conn->query("SELECT id FROM users WHERE login_id='PROF-0001'")->fetch_assoc()['id']; $cci=college_id('CCI');
$conn->query("INSERT IGNORE INTO professors(user_id,employee_id,college_id) VALUES($prof_uid,'PROF-0001',$cci)");
$conn->query("INSERT IGNORE INTO users(fullname,login_id,email,password,role,status) VALUES('Demo Student','2026-0001-A','student@gmail.com','$studpass','student','approved')");
$stud_uid=(int)$conn->query("SELECT id FROM users WHERE login_id='2026-0001-A'")->fetch_assoc()['id'];
$conn->query("INSERT IGNORE INTO students(user_id,student_id,college_id,program_id,year_level,semester_level) VALUES($stud_uid,'2026-0001-A',$cci,$bscs,1,1)");
echo '<h2>Installation complete!</h2><p>Login: REG-0001/admin123, PROF-0001/prof123, 2026-0001-A/student123</p><p><a href="auth/login.php">Go to login</a></p>';
?>
